packaging_format = 2

id = "satdress"
name = "Satdress"
description.en = "Federated Lightning addresses server"
description.fr = "Serveur d'adresses Lightning fédéré"

version = "0.7.2~ynh3"

maintainers = ["Navan Chauhan"]

[upstream]
license = "MIT"
demo = "https://github.com/nbd-wtf/satdress"
admindoc = "https://github.com/nbd-wtf/satdress"
userdoc = "https://github.com/nbd-wtf/satdresss"
code = "https://github.com/nbd-wtf/satdress"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap =  false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.site_name]
    ask.en = "Site name to be displayed"
    ask.fr = "Nom du site à afficher"
    type = "string"
    example = "YUNOSatdress"

    [install.site_owner]
    ask.en = "Site owner handle to be displayed"
    ask.fr = "Identifiant du propriétaire du site à afficher"
    type = "string"
    example = "@yhuser"

    [install.site_owner_url]
    ask.en = "Site owner's URL to be displayed"
    ask.fr = "URL du propriétaire du site à afficher"
    type = "string"
    example = "https://t.me/someuser"

    [install.init_main_permission]
    help.en = "Allow non-YunoHost users"
    help.fr = "Autoriser les utilisateurs non-YunoHost"
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/nbd-wtf/satdress/archive/refs/tags/v0.7.2.tar.gz"
        sha256 = "1f7ec9987ee5d84aa8da6e96f8a5028fe1e391b6cdb3fd3cce3b637701645972"
        autoupdate.strategy = "latest_github_tag"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
