test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    args.randomstring = "BUISDF3"
	args.sitename="zamn"
	args.siteowner="@zamn"
	args.siteownerurl="https://zamn.com"
